CREATE DATABASE EMART1;

USE EMART1;

CREATE TABLE BUYERS(
    BID INT PRIMARY KEY AUTO_INCREMENT,
    FNM VARCHAR(150) NOT NULL,
    LNM VARCHAR(150) NOT NULL,
    EML VARCHAR(200) NOT NULL,
    MBN CHAR(20) NOT NULL,
    DNO VARCHAR(150) NOT NULL,
    STRT VARCHAR(150) NOT NULL,
    CITY VARCHAR(150) NOT NULL,
    PINC VARCHAR(150) NOT NULL,
    UID INT REFERENCES USERS(UID) 
);

CREATE TABLE SELLERS(
    SID INT PRIMARY KEY AUTO_INCREMENT,
    FNM VARCHAR(150) NOT NULL,
    LNM VARCHAR(150) NOT NULL,
    EML VARCHAR(200) NOT NULL,
    MBN CHAR(20) NOT NULL,
    DNO VARCHAR(150) NOT NULL,
    STRT VARCHAR(150) NOT NULL,
    CITY VARCHAR(150) NOT NULL,
    PINC VARCHAR(150) NOT NULL,
    CPNM VARCHAR(150) NOT NULL,
    DSID INT REFERENCES DISCOUNTS(DSID)
);

CREATE TABLE CATEGORIES(
    CTID INT PRIMARY KEY AUTO_INCREMENT,
    CTNM VARCHAR(150) NOT NULL,
    GST  NUMERIC

);

CREATE TABLE SUB_CATEGORIES(
    SUBID INT PRIMARY KEY AUTO_INCREMENT,
    SUBNM VARCHAR(150) NOT NULL,
    CTID INT REFERENCES CATEGORIES(CTID)

);

CREATE TABLE PRODUCTS(
    PID INT PRIMARY KEY AUTO_INCREMENT,
    PNM VARCHAR(150) NOT NULL,
    PRICE NUMERIC,
    DSCP VARCHAR(1000),
    SUBID INT REFERENCES SUB_CATEGORIES(SUBID)
);

CREATE TABLE USERS(
    UID INT PRIMARY KEY AUTO_INCREMENT,
    UNM VARCHAR(150) NOT NULL,
    PWD  VARCHAR(10000)NOT NULL,
    ROLE VARCHAR(30) NOT NULL
);

CREATE TABLE TRANSACTIONS(
    TXNID INT PRIMARY KEY AUTO_INCREMENT,
    TXNM VARCHAR(150) NOT NULL,
    PRICE NUMERIC,
    TXNDT DATE,
    TTYPE INT,
    DSCP VARCHAR(250),
    BID INT REFERENCES BUYERS(BID)
);
CREATE TABLE DISCOUNTS(
    DSID INT PRIMARY KEY AUTO_INCREMENT,
    PRCT NUMERIC NOT NULL,
    SDT DATE NOT NULL,
    EDT DATE NOT NULL,
    MAXC INT
);

CREATE TABLE ORDERS(
    OID INT PRIMARY KEY AUTO_INCREMENT,
    ODT DATE,
    TPRICE NUMERIC NOT NULL,
    DSID INT REFERENCES DISCOUNTS(DSID)
);
CREATE TABLE ORDER_DETAILS(
    ODID INT PRIMARY KEY AUTO_INCREMENT,
    QTY NUMERIC,
    PRICE NUMERIC,
    TPRICE NUMERIC,
    OID INT REFERENCES ORDERS(OID),
     PID INT REFERENCES PRODUCTS(PID),
);
